### ISSUE TITLE
Algorithm not executeable

### ISSUE THREAD

**Issue by N0Dr4m4L4m4** [AlexandreChenu/DCIL#1]
Hey there,

i am trying to execute the DCIL algortihm but for now it is not possible to execute. I was trying at the newest commit but it always sais 

> Traceback (most recent call last):
  File "run_DCIL_maze.py", line 319, in <module>
    total_nb_timesteps = learn_DCIL(args, env, eval_env, dir_path)
  File "run_DCIL_maze.py", line 191, in learn_DCIL
    eval_traj, skills_successes, max_zone = eval_trajectory_mazeenv(env, eval_env, model, args["algo_type"])
  File "/home/DCIL/evaluate/dubinsmazeenv/evaluate_mazeenv.py", line 46, in eval_trajectory_mazeenv
    obs = eval_env.get_obs()
AttributeError: 'DubinsMazeEnvGCPHERSB3' object has no attribute 'get_obs'

I was looking around the code and i saw that one of the last commits changed the function _get_obs()_ (before it was _get_obs()). When I correct that one is seems to work:

> | skills/
|    nb of successfull skill-rollouts:  1
|    total nb of skill-rollouts =  8
|    success ratio (successful rollouts / total rollouts) =   0.125
|    skill-chaining:  [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
|    skill-chaining success:  False
| rollout/           |             |
|    ep_len_mean     | 13.2        |
|    ep_rew_mean     | 0.071428575 |
| time/              |             |
|    episodes        | 70          |
|    fps             | 134         |
|    time_elapsed    | 6           |
|    total_timesteps | 924         |
...

Actually after some time there is also another error incoming:

> Traceback (most recent call last):
  File "run_DCIL_maze.py", line 319, in <module>
    total_nb_timesteps = learn_DCIL(args, env, eval_env, dir_path)
  File "run_DCIL_maze.py", line 221, in learn_DCIL
    model.train(batch_size=model.batch_size, gradient_steps=gradient_steps)
  File "/home/DCIL/algos/SAC_DCIL.py", line 268, in train
    replay_data, infos =  self.replay_buffer.sample(batch_size, env=self._vec_normalize_env)
ValueError: too many values to unpack (expected 2)

When i try to run some other version of DCIL it sais the same thing with the buffer error.

What can I do?

**Comment by AlexandreChenu** [comment]
Hi Robin, 
I'm sorry for not getting back to you sooner, but I'm a bit inactive at the moment.  
I have stopped using SB3 since this last commit. I'll take a closer look at the error as soon as I can. 
In the meantime, I recommend you test this code for a newer version of DCIL based on our jax-based library XPAG: https://github.com/AlexandreChenu/DCIL_XPAG
Overall, the code is (a bit) cleaner. But most importantly, the underlying library is lighter. 
Alex
